CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,7 @@ env:
   PY_VER: '3.14'
 
 jobs:
-  CI:
+  execute:
     runs-on: self-hosted
     steps:
     - name: Checkout repository
@@ -32,6 +32,10 @@ jobs:
       id: setup-python
       with:
         python-version: ${{ env.PY_VER }}
+    - name: Install the latest version of uv
+      uses: astral-sh/setup-uv@v7
+    - name: Install Python dependencies
+      run: uv pip install --system -r requirements.txt
     - name: Read Julia version
       id: julia-version
       run: python -c 'import tomllib; from pathlib import Path; print("value=", tomllib.loads(Path("Manifest.toml").read_text())["julia_version"], sep="")' >> "$GITHUB_OUTPUT"
@@ -72,9 +76,12 @@ jobs:
         Pkg.instantiate()
         Pkg.resolve()
         Pkg.precompile()
+        Pkg.activate()
+        Pkg.add(["JSON", "Literate", "MarkdownTables", "SHA", "Tables"])
         if ENV["RUNNER_ENVIRONMENT"] == "github-hosted"
             Pkg.gc(;collect_delay=Day(0))
         end
+        using Literate
     - name: Save Julia packages
       uses: actions/cache/save@v5
       if: ${{ steps.cache-nb.outputs.cache-hit != 'true' && runner.environment == 'github-hosted' && steps.cache-julia.outputs.cache-hit != 'true' }}
@@ -84,15 +91,27 @@ jobs:
     - name: Run notebooks
       if: ${{ steps.cache-nb.outputs.cache-hit != 'true' }}
       run: julia --project=@. --color=yes -p ${{ env.LITERATE_PROC }} .github/ci.jl
+    - name: Upload Notebook
+      uses: actions/upload-artifact@v6
+      with:
+        name: notebooks
+        path: ${{ env.NBCACHE }}
+        include-hidden-files: true
+  render:
+    needs: execute
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v6
+    - name: Download notebooks
+      uses: actions/download-artifact@v7
+      with:
+        name: notebooks
+        path: ${{ env.NBCACHE }}/
     - name: Copy back built notebooks
       run: |
         cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
         find docs/ -type f -name "*.jl" -delete
-    - name: Upload notebook
-      uses:  actions/upload-artifact@v6
-      with:
-        name: notebooks
-        path: docs/**/*.ipynb
     - name: Setup Quarto
       if: ${{ runner.environment == 'github-hosted' }}
       uses: quarto-dev/quarto-actions/setup@v2
@@ -103,10 +122,23 @@ jobs:
       if: ${{ github.ref == 'refs/heads/main' }}
       with:
         path: docs/_site/
-
+  # CI conclusion for GitHub status check
+  CI:
+    needs: render
+    if: always()
+    runs-on: ubuntu-slim
+    steps:
+      - run: |
+          if [[ ${{ needs.render.result }} == "success" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
   deploy:
     name: Deploy to GitHub pages
-    needs: CI
+    needs: render
     if: ${{ github.ref == 'refs/heads/main'}}
     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
     permissions:
